name: Windows CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        vulkan-version: [1.1.126.0]

    runs-on: windows-latest
    env:
      VULKAN_SDK: C:\VulkanSDK\${{ matrix.vulkan-version }}      

    steps:
    - uses: actions/checkout@v1
    # Reference: https://github.com/GPSnoopy/RayTracingInVulkan/blob/057dfaf56df07afebec8d7112add32ccbc8160b4/.github/workflows/windows.yml
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${{ matrix.vulkan-version }}/windows/VulkanSDK-${{ matrix.vulkan-version }}-Installer.exe?Human=true" -OutFile VulkanSDK.exe -v
    - name: Install Vulkan SDK
      run: .\VulkanSDK.exe /S
      shell: cmd
    - run: echo "::add-path::C:\VulkanSDK\${{ matrix.vulkan-version }}\bin"
    - name: Check Vulkan SDK
      run: |
        dir
        dir C:\
        dir C:\VulkanSDK
        dir C:\VulkanSDK\${{ matrix.vulkan-version }}
        set
      shell: cmd
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install meson
    - uses: ilammy/msvc-dev-cmd@v1
      env:
        arch: x64
    - run: meson --buildtype "release" --prefix $pwd\output --bindir x64 --libdir x64 -Denable_tests=false buildx64
    - run: ninja install -C buildx64
