name: Windows CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        vulkan-version: [1.1.126.0]

    runs-on: windows-latest
    env:
      VULKAN_SDK: C:\VulkanSDK\${{ matrix.vulkan-version }}      

    steps:
    - uses: actions/checkout@v1
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${{ matrix.vulkan-version }}/windows/VulkanSDK-${{ matrix.vulkan-version }}-Installer.exe?Human=true" -OutFile VulkanSDK.exe -v
    - name: Install Vulkan SDK
      run: .\VulkanSDK.exe /S
      shell: cmd
    - name: Check Vulkan SDK
      run: |
        dir
        dir C:\
        dir C:\VulkanSDK
        dir C:\VulkanSDK\${{ matrix.vulkan-version }}
        set
      shell: cmd